const MenuAPI = [
  {
    id: 1,
    image: "Images/lunch-4.jpg",
    name: "Rice Food ",
    category: "lunch",
    price: "$8.80",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 2,
    image: "Images/brackfast-2.jpg",
    name: "Muesl",
    category: "brackfast",
    price: "$5.20",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 3,
    image: "Images/evening-4.jpg",
    name: "rice flour Ruti",
    category: "evening",
    price: "$3.80",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 4,
    image: "Images/brackfast-4.jpg",
    name: "Curd Upma",
    category: "brackfast",
    price: "$6.50",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 5,
    image: "Images/lunch-1.jpg",
    name: "Egg Biryani",
    category: "lunch",
    price: "$10.50",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 6,
    image: "Images/lunch-2.jpg",
    name: "Chole Biryani",
    category: "lunch",
    price: "$16.50",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 7,
    image: "Images/lunch-3.jpg",
    category: "lunch",
    name: "Plain Biryani",
    price: "$13.50",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 8,
    image: "Images/brackfast-1.jpg",
    name: "Brackfast",
    category: "brackfast",
    price: "$5.00",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 9,
    image: "Images/lunch-5.jpg",
    name: "Pineapple Fried Rice",
    category: "lunch",
    price: "$12.50",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 10,
    image: "Images/evening-1.jpg",
    name: "Moong Dhal Dhokla",
    category: "evening",
    price: "$6.50",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 11,
    image: "Images/evening-2.jpg",
    name: "Singera & Comucha",
    category: "evening",
    price: "$5.50",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 12,
    image: "Images/evening-3.jpg",
    name: "Milk Tea & Bakhary",
    category: "evening",
    price: "$6.50",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },

  {
    id: 13,
    image: "Images/evening-5.jpg",
    name: "Bakhary, Nooduls & milk",
    category: "evening",
    price: "$4.50",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 14,
    image: "Images/brackfast-3.jpg",
    name: "Tomato Poha",
    category: "brackfast",
    price: "$4.00",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 15,
    image: "Images/dinner-1.jpg",
    name: "Hard tacos",
    category: "dinner",
    price: "$13.00",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 16,
    image: "Images/dinner-2.jpg",
    name: "Stir fry",
    category: "dinner",
    price: "$11.80",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 17,
    image: "Images/dinner-3.jpg",
    name: "Burritos",
    category: "dinner",
    price: "$9.50",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 18,
    image: "Images/dinner-4.jpeg",
    name: "Meatballs & rice",
    category: "dinner",
    price: "$12.50",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 19,
    image: "Images/dinner-5.jpg",
    name: "Pot roast",
    category: "dinner",
    price: "$14.00",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 20,
    image: "Images/dinner-6.jpg",
    name: "Shepherd's pie",
    category: "dinner",
    price: "$11.50",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 21,
    image: "Images/ice-cream-1.jpg",
    name: "Nut & Chocolate",
    category: "ice-cream",
    price: "$5.30",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
  {
    id: 22,
    image: "Images/ice-cream-2.jpg",
    name: "Chocolate",
    category: "ice-cream",
    price: "$6.00",
    description: "Lorem ipsu dolor sit amet, and me to consectetur adipisicing elit. Dol, esse. and  consectetur.",
  },
];

export default MenuAPI;
